---
name: Create repository

inputs:
  base_path:
    default: .
    description: Base path
    required: false
  el_version:
    description: The EL version ('el_version' + '/' is prepended to 'repo_dirname' & appended to 'image_prefix')
    required: true
  image_prefix:
    default: ghcr.io/${{ github.repository }}/
    description: Image Prefix
    required: false
  image_registry:
    default: ghcr.io
    description: Image Registry
    required: false
  repo_dirname:
    default: ${{ github.ref_name }}
    description: Repository directory name
    required: false
  repo_parent_dir:
    default: /tmp/repos
    description: Repository parent directory
    required: false
  rpms_dir:
    default: RPMS
    description: RPMs directory
    required: false

runs:
  using: composite

  steps:
    - name: Log in to GHCR
      uses: radiant-maxar/geoint-actions/docker/registry-login@v1.1
      with:
        server: ${{ inputs.image_registry }}

    - name: Create repository
      env:
        COMPOSE_FILE: docker-compose.${{ inputs.el_version }}.yml
        IMAGE_PREFIX: ${{ inputs.image_prefix }}${{ inputs.el_version }}/
        REPO_DIR: ${{ inputs.repo_parent_dir }}/${{ inputs.el_version }}/${{ inputs.repo_dirname }}
      run: |
        make --makefile=Makefile.${{ inputs.el_version }} rpmbuild-generic
        mkdir --parents ${REPO_DIR}
        cp --verbose ${{ inputs.rpms_dir }}/*/*.rpm ${REPO_DIR}/
        docker-compose run -T \
          -v ${PWD}/scripts:/rpmbuild/scripts:ro \
          -v ${REPO_DIR}:${REPO_DIR}:rw \
          rpmbuild-generic \
            bash -c "scripts/repo-update.sh ${REPO_DIR}"
      shell: bash --noprofile --norc -euxo pipefail {0}
      working-directory: ${{ inputs.base_path }}
